<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.6 on win32)" generated="20220901 10:36:46.864" rpa="false" schemaversion="3">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="DDT2 Excel" source="C:\Users\Saurabh\PycharmProjects\Automation\TestCases\DDT2_Excel.robot">
<kw name="Open My Browser" library="Login_Resources" type="SETUP">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${LOGIN URL}</arg>
<arg>${BROWSER}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20220901 10:36:47.192" level="INFO">Opening browser 'Firefox' to base url 'https://admin-demo.nopcommerce.com/login?returnurl=%2Fadmin%2F'.</msg>
<msg timestamp="20220901 10:36:47.192" level="INFO">Firefox driver log is always forced to to: C:\Users\Saurabh\PycharmProjects\Automation\Results\pabot_results\4\geckodriver-1.log</msg>
<status status="PASS" starttime="20220901 10:36:47.192" endtime="20220901 10:36:55.348"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20220901 10:36:55.349" endtime="20220901 10:36:55.353"/>
</kw>
<status status="PASS" starttime="20220901 10:36:47.191" endtime="20220901 10:36:55.354"/>
</kw>
<test id="s1-s1-t1" name="LoginTestwithcsv" line="12">
<kw name="Invalid login">
<arg>${username} and ${Password}</arg>
<msg timestamp="20220901 10:36:55.360" level="FAIL">Variable '${username}' not found.</msg>
<status status="FAIL" starttime="20220901 10:36:55.357" endtime="20220901 10:36:55.360"/>
</kw>
<status status="FAIL" starttime="20220901 10:36:55.355" endtime="20220901 10:36:55.364">Variable '${username}' not found.</status>
</test>
<kw name="Close Browser" library="SeleniumLibrary" type="TEARDOWN">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20220901 10:36:55.365" endtime="20220901 10:36:56.723"/>
</kw>
<status status="FAIL" starttime="20220901 10:36:46.900" endtime="20220901 10:36:56.723"/>
</suite>
<status status="FAIL" starttime="20220901 10:36:46.880" endtime="20220901 10:36:56.725"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="DDT2 Excel">Suites.DDT2 Excel</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220901 10:36:47.190" level="ERROR">Error in file 'C:\Users\Saurabh\PycharmProjects\Automation\TestCases\DDT2_Excel.robot' on line 5: Importing library 'DataDriver' failed: ModuleNotFoundError: No module named 'DataDriver'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Saurabh\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  C:\Users\Saurabh\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\Saurabh\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\Saurabh\AppData\Local\Programs\Python\Python310\lib
  C:\Users\Saurabh\AppData\Local\Programs\Python\Python310
  C:\Users\Saurabh\AppData\Local\Programs\Python\Python310\lib\site-packages</msg>
</errors>
</robot>
